### PR TITLE
Upgrade 'electron' to '21.3.0'

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

Upgrade `electron` to `21.3.0`

#### Motivation and Context

[Changelog](https://github.com/electron/electron/releases/tag/v21.3.0)

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
I'm experiencing MS Teams crashing as soon as I join a video call (with my audio and video turned off). This was working in the previous nightly (and re-verified by rolling back to the published nightly as well). I suspect something related to this upgrade. can someone else please check? Till then I'm not merging this PR into the develop branch
cc @SpecialAro @kris7t @muhamedsalih-tw @balajiv113 @Alphrag

**Comment by balajiv113** [comment]
Teams updated their call feature in browser recently. From then even the call in chrome is lot slower. Maybe this has to do something with that ?

I will give a try in sometime and see what's happening

**Comment by vraravam** [comment]
@balajiv113 @Alphrag - were you able to test a Teams screen sharing or video con call? This morning there was another upgrade to electron which I have incorporated into this PR. Please verify - so that we can merge this PR to get the security patches from chromium

**Comment by Alphrag** [comment]
>  Please verify - so that we can merge this PR to get the security patches from chromium

@vraravam I've tried it with Jitsi and teems on my mac, it runs perfectly fine on my end! 🙂

**Review by Alphrag — APPROVED** [review]

**Comment by vraravam** [comment]
I didn;t realize it, but I had been running this latest version all day today and was on multiple Teams meetings without issues - lol

**Pull request merged**
