### PR TITLE
chore: servicesStore + models into typescript

### PR DESCRIPTION
**Pull request by cino**
- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
- ServicesStore => typescript
- Recipe/Service modal => typescript
- Modified jsUtils to contain a generic ifUndefined

#### Motivation and Context
#42 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by vraravam — APPROVED** [review]

**Comment by vraravam** [comment]
@cino - I assume you have run these changes locally in the packaged mode?

**Comment by vraravam** [comment]
@cino - please see the issue that I faced:
Screenshot 2022-06-23 at 9 05 19 PM

This is for MS Teams service - which was running quite fine a few seconds before without your changes. Please retest.

**Review by vraravam — CHANGES_REQUESTED** [review]
please see above comment

**Comment by cino** [comment]
@vraravam Yep. Actually running the packaged build right now. How/when are you seeing that issue? Not seeing that myself at the moment. 

Edit: MS Teams, gotcha, let me check that.

**Comment by vraravam** [comment]
ok - must have been some other temp race condition. I restarted the packaged Ferdium with your changes - and now it works. Thanks!

**Review by vraravam — APPROVED** [review]

**Comment by vraravam** [comment]
ok - i think we lost the unread counts for all services with this change though
Screenshot 2022-06-23 at 9 23 45 PM

Update: yes, confirmed that the `develop` branch code doens't have this issue

**Comment by cino** [comment]
That latest error message should've been fixed by my last commit cause I saw that as well.

**Comment by vraravam** [comment]
Screenshot 2022-06-23 at 9 31 58 PM

Just verified that the build I am running is the same as your latest commit

**Comment by vraravam** [comment]
ok - with that latest commit, things are back to normal! tx!

**Pull request merged**
