### PR TITLE
Create GH Action for automatic publish of releases

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Create GH Action for automatic publish of releases

#### Motivation and Context
Create GH Action for automatic publish of releases. This connects to an account bot on reddit and publishes information on new releases.

Given that I haven't tested it locally (short time to do that). I'm creating this PR to publish to a test subreddit (r/ferdiumtests) before changing it to the main subreddit. Once this works we just have to change the corresponding commented lines.

Also, I don't seem to have access to set secrets on this repository (so as to set the needed secrets for this PR). Will anyone be able to give me those perms or should I send those over to someone? Thank you!

#### Checklist

- [x] My pull request is properly named

#### Release Notes
Create GH Action for automatic publish of releases

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
I haven't tested this. and I dont want to merge this until the secrets are in place.
@SpecialAro - please add the secrets in and then merge?

**Comment by SpecialAro** [comment]
> I haven't tested this. and I dont want to merge this until the secrets are in place.
> @SpecialAro - please add the secrets in and then merge?

Yes, i don't want to merge it without the secrets in place as well... It will fail without them.

I don't have the necessary perms to add secrets to this repo, I asked @dqos if he can provide me access to it yesterday but maybe he still didn't had the change to look into it.

**Comment by SpecialAro** [comment]
Thank you @vraravam ! Secrets, added :D merging this now!

**Comment by SpecialAro** [comment]
https://github.com/ferdium/ferdium-app/actions/runs/2524274904/workflow

Build is failing on "with" statement. Can be due to the [Release] tag on the "title" part.

**Comment by vraravam** [comment]
Could you take a pass at fixing this pls @SpecialAro ? If not, I can take a look later today?

**Comment by SpecialAro** [comment]
> Could you take a pass at fixing this pls @SpecialAro ? If not, I can take a look later today?

I can try to look at it in a minute. But I can't really understand why it is failing... Doesn't make much sense

**Pull request merged**
