### PR TITLE
Feature: Progress Indicator for page loading

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Feature: Progress Indicator for page loading

#### Motivation and Context
Feature: Progress Indicator for page loading. Helps fix partially #239.

#### Screenshots
Animation

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Feature: Progress Indicator for page loading

### CODE REVIEW

**Review by vraravam — APPROVED** [review]

**Comment by HenrijsS** [comment]
@SpecialAro What would you think about a more subtle Progressbar at the top?

Here's an easy library for it: https://kimmobrunfeldt.github.io/progressbar.js/

**Comment by kris7t** [comment]
This might also partially fix https://github.com/ferdium/ferdium-app/issues/157

**Comment by SpecialAro** [comment]
> This might also partially fix https://github.com/ferdium/ferdium-app/issues/157

For real? 🧐 Wasn't looking for that issue when coding, but I might have a hint on what's going wrong there... I think we might be handling event listeners wrongly, and that the variable `isLoading` doesn't turn to false when it should (stumbled across some problems, that's why I implemented another variable and added a new event listener as well).

**Comment by kris7t** [comment]
well, it seems you also set `isLoading = false` in the `did-stop-loading` listener https://github.com/ferdium/ferdium-app/pull/248/files#diff-17d0da31b2d63aba19230c37f8f83212930e7493a7895464981c50897cfc4844R395 -- if that didn't mess up something else (like handling crashes during page loading or something), then the loader should have potentially became more robust. At least that's what I have observed when playing around with `BrowserView`: https://github.com/ferdium/ferdium-app/issues/157#issuecomment-1153215048 (which is a very different thing from from `<webview>`, so I'm not 100% certain the same fix could apply here).

But I still have no clue in what order should the various events fire on page loading...

**Comment by OskarEichler** [comment]
@SpecialAro @vraravam To be honest I find this implementation incredibly annoying - now the Loading square is taking over every single time I type in Whatsapp or switch pages and is super distracting. Appreciate the thought of a loading indicator, but it should be less intrusive for sure! 

Maybe do something like a thin progress bar on the top or just a small loading indicator in the icon on the left side or something that is much more nuanced than a full page takeover in the middle of the screen please! 

Normal browsers like Chrome and Firefox don't do this either, so users are already used to the behavior of waiting for a short amount of time after interacting on a site. This feels like overkill. Or maybe make it an optional setting for us to turn off.

**Comment by vraravam** [comment]
There's this https://www.npmjs.com/package/react-topbar-progress-indicator which can be less obstrusive. @SpecialAro - could you implement this? or shall i try later tonight after work?

**Comment by SpecialAro** [comment]
> There's this https://www.npmjs.com/package/react-topbar-progress-indicator which can be less obstrusive. @SpecialAro - could you implement this? or shall i try later tonight after work?

Hey 👋
The next couple of days (today and tomorrow) will be difficult for me (as I have two weddings to be at) so if you can try I would really appreciate it!

I'll be available for anything you need on discord during the process, but won't be able to get my hands on a computer 🙈

**Comment by pepper3k** [comment]
This is perfect!
Side note: I would suggest sticking with the ferdium color scheme (purple shade) so the appearance is consistent.

**Comment by gustavotrott** [comment]
It would be good if I could disable it for a specific service!
I'm using WhatsApp and it is showing this Loading indicator very often and disrupting the usability.

**Comment by vraravam** [comment]
@gustavotrott - the upcoming nightly (probably in an hour or so) will fix this.

**Comment by OskarEichler** [comment]
@vraravam The progress bar is much better! Thanks for the swift implementation! Some feedback:

1. The progress bar is still very jittery for Whatsapp (maybe only display after a slight delay, so that when a lot of loads happening very quickly after one another it doesn't jitter like that and only starts displaying when a lot takes longer than 0.2 seconds or something along those lines)
2. Make the progress bar optional per service or add a global on/off toggle for users to decide if they want it or not
3. Right now the color is some rainbow gradient - would be cool to use the same color that was set in Settings > Appearance > Accent Color Settings

**Comment by vraravam** [comment]
@OskarEichler :
1. Delayed + Merged action: The [npm package that I found](https://www.npmjs.com/package/react-topbar-progress-indicator), does not have this capability. By inferring what you want, you are also referring to the ability to "merge" multiple such load events into one, so that the progress-bar can suitably show completion status. Again, this is not present in the library.
2. Optional per service: I can try this out over this weekend - no promises though
3. If using the same as the accent color, then there's no visible difference between the progress bar and the window title (over which the progress bar is rendered). This will effectively make it useless. Instead, we would need to add another user-specifiable option which could then be injected for the progress bar configuration. More work, will try, no promises.

**Comment by OskarEichler** [comment]
Sounds good, thank you @vraravam 

1. I'm more thinking that you only mount TopBarProgress with a delay of 0.2 seconds / if this.state.loading is still true after 0.2 seconds. There really is no need to show the progress bar for such short loading times and keep mounting and unmounting the component as it will just jitter onscreen. If you add a small delay function then it will only mount the component when it's actually a longer load, for which a loading indication is helpful. 

2. Awesome thank you!

3. Regarding accent color - on Mac there is no window title, so I'm not seeing that. Why not use a different shade of the primary color? In Accent Color Settings it's possible to set the primary color, and then choose between 5 different shades of brightness levels. Could just choose a lighter / darker version from the user setting so that there is a distinct difference, but it still fits the users settings and doesn't require a whole new color picker.

**Comment by vraravam** [comment]
>     1. I'm more thinking that you only mount TopBarProgress with a delay of 0.2 seconds / if this.state.loading is still true after 0.2 seconds. There really is no need to show the progress bar for such short loading times and keep mounting and unmounting the component as it will just jitter onscreen. If you add a small delay function then it will only mount the component when it's actually a longer load, for which a loading indication is helpful.

I'm not a js/css dev, so won't be able to accomplish your recommendation. Will let one of the other contributors take a shot at this.

>     3. Regarding accent color - on Mac there is no window title, so I'm not seeing that. Why not use a different shade of the primary color? In Accent Color Settings it's possible to set the primary color, and then choose between 5 different shades of brightness levels. Could just choose a lighter / darker version from the user setting so that there is a distinct difference, but it still fits the users settings and doesn't require a whole new color picker.

But, here's the PR with a screenshot of the user-controllable progress bar: #291

**Comment by gustavotrott** [comment]
Unfortunatelly the  less-obstrusive progress bar didn't help for WhatsApp.
The service become very slow because the hectic progress bar.

Once WhatsApp is the main service I use, I had to downgrade to 6.0.0-nightly.60 to be usable.

**Comment by kris7t** [comment]
@gustavotrott You should be able to disable the progress bar per service as per https://github.com/ferdium/ferdium-app/pull/301

**Comment by gustavotrott** [comment]
> @gustavotrott You should be able to disable the progress bar per service as per #301

Awesome! Thanks

**Pull request merged**
