### PR TITLE
Fix arm builds

### LINKED ISSUE #1360: Updating nightly version nukes all my services
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

macOS

### Operating System Version

Ventura 13.2.1 (22D68)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

_No response_

### Expected Behavior

update should keep the app working as usual

### Actual Behavior

All services are deleted and it's not possible to add them back.  I have to reinstall the dmg from the website.

### Steps to reproduce

click "restart and install update" on the nightly build update button
that's it

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### LINKED ISSUE #1387: 6.5.0 release - broken services
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.0

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura 13.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.4.1

### Expected Behavior

After upgrade the app should still be working and load all the configured services

### Actual Behavior

All the services are gone and there are multiple errors happening in the developer tools (check the screenshot)

### Steps to reproduce

Upgrade 6.4.1 to 6.5.0.

### Debug link

https://debug.ferdium.org/4ce726cc-f27c-496b-b0af-e8ef9939c4af

### Screenshots

Screenshot 2023-10-02 at 21 08 00

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
Co-authored-by: André Oliveira <oliveira.andrerodrigues95@gmail.com>
(cherry picked from commit f669badf1908284de591ab12399fc3e7ee0c311a)

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Fix arm builds (all OS) and add back (necessary) tweak on `pnpm.cjs` for Windows builds

#### Motivation and Context
This PR closes https://github.com/ferdium/ferdium-app/issues/1360 and https://github.com/ferdium/ferdium-app/issues/1387
Thank you @Alphrag for working on this with my (minor) help!
Thank you @ylluminate and @bkimmett for the endless testing on `arm` machines!

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
fix: make `arm` builds work again

### CODE REVIEW

**Comment by ylluminate** [comment]
Are we waiting for a nightly build or is one in the pipeline?

**Comment by sscotth** [comment]
> Are we waiting for a nightly build or is one in the pipeline?

Running right now...

https://github.com/ferdium/ferdium-app/actions/runs/6553146197

.... and its done.

**Comment by SpecialAro** [comment]
> Are we waiting for a nightly build or is one in the pipeline?

Sorry! Yes, it is published as 6.5.2-nightly.4 or 6.5.2

**Comment by ylluminate** [comment]
Wonderful, it's in place now, services updated and all seem right now! Oddly enough it feels even a little snappier than before.

**Pull request merged**
