### PR TITLE
chore: featureStore and GlobalErrorStore JS => TS

### PR DESCRIPTION
**Pull request by cino**
- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
- Turned the FeatureStore and GlobalErrorStore into typescript
- Improved store.types.ts by extending a base Store with default props
- Improved gulp to include JSX files
- renamed app.js to app.jsx to get rid of JSX warnings, which should be TSX in the future.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
none

### CODE REVIEW

**Comment by cino** [comment]
Not entirely sure why these changes are showing from the submodule recipes. If anyone could explain :)

**Comment by SpecialAro** [comment]
> Not entirely sure why these changes are showing from the submodule recipes. If anyone could explain :)

You're probably not using the build script to update the submodule to the most recent commit... then, when you do `git add .` it adds the difference of the submodule

**Review by SpecialAro — APPROVED** [review]
LGTM. Previewed locally without any issue.

Thank you again @cino , for this PR about TS conversion 😄

**Comment by cino** [comment]
@SpecialAro Ah, that makes sense! Will make sure next time.

**Review by vraravam — APPROVED** [review]
Haven't tested this locally - assuming it works

**Comment by vraravam** [comment]
@cino - please resolve the conflicts before this can be merged

**Review by vraravam — APPROVED** [review]

**Comment by vraravam** [comment]
@cino - GH still reports a merge conflict. I would suggest that you rebase from the `origin/develop` branch (after pulling) and resolve the conflicts. Once done, you should be able to force-push to your remote PR branch

**Review by vraravam — APPROVED** [review]

**Pull request merged**
