### PR TITLE
Update colors in branding README

### PR DESCRIPTION
**Pull request by Arthur-Huan**
The gradient description is oudated.

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

I tested the current gradient description, and it seems to be an older washed-out gradient (like the Ferdi gradient here: https://appimage.github.io/Ferdi/), so I updated the hex codes and the gradient direction.
#### Motivation and Context

I was unable to use the current branding information to create the correct logo for my app menu (I use rounded square logos), but I'm sure there are way more benefits to having up-to-date branding information.

#### Screenshots

Logo made with current gradient information:
image
Logo with updated gradient information:
image

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [ ] `pnpm test` passes
- [ ] I tested/previewed my changes locally

#### Release Notes

Updated the color values for branding.

### CODE REVIEW

**Comment by marie-bnl** [comment]
Are there objective reasons why the current branding should be modified? I don’t understand what you mean by “outdated” and “up-to-date”.

**Comment by Arthur-Huan** [comment]
> Are there objective reasons why the current branding should be modified? I don’t understand what you mean by “outdated” and “up-to-date”.

The hex codes do not correspond to the actual colors in the logo.

**Comment by marie-bnl** [comment]
Oh my bad, that’s right.

**Review by SpecialAro — APPROVED** [review]
LGTM, approving and merging as this is coherent with https://github.com/ferdium/ferdium-branding/blob/main/gradient/gradient.svg

**Pull request merged**
