### PR TITLE
Enable snap build & publish

### PR DESCRIPTION
**Pull request by NathanaelGandhi**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

- [x] Uncomment build target snap in electron-builder.yaml
- [x] Uncomment publish for edge, beta, stable channels in github builds.yaml
- [x] Created snapcraft login & "ferdium" app
- [x] Generated SNAPCRAFT_LOGIN secret
- [x] Added SNAPCRAFT_LOGIN to GH secrets | added by @vraravam 

#### Motivation and Context

#52 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)

#### Release Notes

Enabled snap package publishing

### CODE REVIEW

**Comment by vraravam** [comment]
@NathanaelGandhi : pls DM me in discord - for setting up the snap secret. I assume you have tested these changes locally?

**Review by vraravam — APPROVED** [review]
Changes seem to only be the revert of the previously working code from ferdi. LGTM after the secret has been setup

**Comment by NathanaelGandhi** [comment]
@vraravam Correct, the changes are only a revert of previous ferdi code, from https://github.com/ferdium/ferdium-app/commit/8330a9299776359001d5e700113b7935e6057df1 and https://github.com/ferdium/ferdium-app/commit/34a2a84c9f217d9aa40b3d74dc0429dad49a4696 that you pointed out to me in #52 . I have reached out on discord PM

**Comment by vraravam** [comment]
@all-contributors please add @NathanaelGandhi for infra

**Pull request merged**
