### PR TITLE
Fix service labels styling

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Fix service labels styling

#### Motivation and Context
This is related to this https://github.com/ferdium/ferdium-app/pull/349#issuecomment-1165806253
Disclaimer: Services with large names provoke an hidden overflow and will look bad.

#### Screenshots
| Before <br /> image| After <br /> image |
|-- |-- |

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by cino — APPROVED** [review]
Nice!

**Comment by SpecialAro** [comment]
> Nice! 

Tho, there is still instability on different sidebar sizes :(

We should do a general review of the styling of Ferdiuk at some point .. we have several files that could be deleted, some css rules that override others and so on..

**Comment by cino** [comment]
Yeah not just the styling, got a feeling once we get to the point of upgrading mobx we can do some proper cleanup. But all part of the process 👌

**Review by vraravam — APPROVED** [review]
Nice job @SpecialAro ! LGTM

**Comment by vraravam** [comment]
btw - only use `[skip ci]` if you are only making changes in documentation and/or Dockerfile and/or say the GH actions for nightly builds. All other changes need a CI build to happen for validation.

**Comment by SpecialAro** [comment]
> btw - only use `[skip ci]` if you are only making changes in documentation and/or Dockerfile and/or say the GH actions for nightly builds. All other changes need a CI build to happen for validation.

Yes, sorry! Next time will do it. I did skip it because css changes generally don't break functionality other than aesthetics 🥲

**Pull request merged**
