### PR TITLE
fix: enable/disable todos menu

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
- Fix the separator on Todos Menu
- Add Disable Todos ability to the Todos Menu

#### Motivation and Context
If you can enable Todos from the Menu, you should be able to disable it too.

#### Screenshots
| Before | After |
|-- |-- |
| image image | image image |

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

fix: enable/disable todos menu

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
I would prefer the enable vs disable to be in the same position on the screen (thus have disable above the "close todos" menu item) - but, that's a personal preference. Feel free to change or merge as-is

**Comment by SpecialAro** [comment]
Changed it, committing now :D
image

**Review by vraravam — APPROVED** [review]
LGTM!

**Review by cino — APPROVED** [review]

**Comment by cino** [comment]
You could also do it like this to de-duplicate the toggle function call; 

```js
    menu.push({
      label: intl.formatMessage(
        !isFeatureEnabledByUser 
          ? menuItems.disableTodos
          : menuItems.enableTodos
      ),
      click: () => {
        todoActions.toggleTodosFeatureVisibility();
      },
      enabled: this.stores.user.isLoggedIn,
    });
    
    if (isFeatureEnabledByUser) {
      menu.push(
        {
          type: 'separator',
        },
        {
          label: intl.formatMessage(drawerLabel),
          accelerator: `${todosToggleShortcutKey()}`,
          click: () => {
            todoActions.toggleTodosPanel();
          },
          enabled: this.stores.user.isLoggedIn && isFeatureEnabledByUser,
        },
      );
    }
```

**Comment by vraravam** [comment]
I have incorporated @cino 's comments from above - please verify once. I am building on my local as well

**Comment by SpecialAro** [comment]
> I have incorporated @cino 's comments from above - please verify once. I am building on my local as well

image
image

It is the other way around (the message is wrong xd)

**Review by vraravam — APPROVED** [review]

**Pull request merged**
