### PR TITLE
Do not allow http urls that end in '/' (fixes #102)

### LINKED ISSUE #102: Bug: If custom server URL ends in "/", app fails to login and signup
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0.nightly.26

### What Operating System are you using?

Other Linux

### Operating System Version

arch linux (rolling release, latest updates as of 5/6/2022)

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

When using a custom server, login and signup from the app should work even if the server URL is terminated with a "/" character.

### Actual Behavior

When the custom server URL is terminated by a "/" (e.g. "https://ferdium.some.site/") neither login nor signup work from the desktop app. No error is displayed, but clicking on the "Sign in" or "Create account" buttons does nothing.

Removing the trailing "/" from the URL (e.g. "https://ferdium.some.site") makes login and signup work again.

### Steps to reproduce

1. Open ferdium app
2. Go to "Change server"
3. In "Server" dropdown, choose "Custom"
4. In "Custom server" enter the URL of a working ferdium-server instance with a trailing /
5. Click "Submit" button
6. Click "Login to your account"
7. Enter credentials and click "Sign in" button
8. Nothing happens
9. Repeat the steps above to remove the trailing / from the server URL and try to log in
10. Login now works

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

My guess is the app uses string concatenation to create the login URL, and when the custom server URL has a trailing / the resulting login URL has a double // somewhere.

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

Add validation when checking for URLs to also validate that it doesn't end in `/`

#### Motivation and Context

Fixes #102 

#### Screenshots

Screenshot 2022-05-05 at 6 22 04 PM
Screenshot 2022-05-05 at 6 22 17 PM

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by kris7t — APPROVED** [review]
LGTM.

An even better solution would be to automatically remove the `/` if it is entered, but I have no idea how to do that with the form components that Ferdium has in place.

**Comment by amatriain** [comment]
This PR makes URLs with a trailing / invalid for the app, but as far as I know such URLs are correct. I don't think considering them invalid is a proper fix. 

I think the root of the problem is here: 

https://github.com/ferdium/ferdium-app/blob/875dedc70a08c2cc132536d18490d89bf34f7335/src/api/server/ServerApi.ts#L50

(this line is for login, there are other lines in the same file that do the same for signup, invite users etc).

The login URL in that line is formed with a simple string concatenation ````${apiBase()}/auth/login````, so if the server URL ends in a / the resulting login URL has a double //, something like ```https://ferdium.some.domain//auth/login```.

I think a better fix would be either:

- compose api URLs with a library that properly handles base URLs and relative paths instead of simple string concatenation.
or
- when saving the base URL, instead of rejecting it if there's a trailing / like what you did here, remove the trailing / character before saving.

**Comment by vraravam** [comment]
Thanks @amatriain - im reverting that fix and will raise a new PR in a few mins. I dont have any way to check - can you please check the new PR before I merge it in?

**Comment by amatriain** [comment]
> Thanks @amatriain - im reverting that fix and will raise a new PR in a few mins. I dont have any way to check - can you please check the new PR before I merge it in?

My setup uses docker images. I guess I would have to generate a new docker image from the new PR to test it. Is there any documentation to help me create a docker image for this project?

**Comment by vraravam** [comment]
There's already a `Dockerfile` in the main repo/codebase. Have you tried with that?

**Comment by amatriain** [comment]
I'm sorry for the delay. I don't really have the time to properly test this, sorry.

**Pull request merged**
