### PR TITLE
chore: upgrade electron to v28.1.3

### PR DESCRIPTION
**Pull request by xduugu**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

- upgraded electron to v28.1.3

#### Motivation and Context

Several fixes for security issues and updated chromium. 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

chore: upgrade electron to v28.1.3

### CODE REVIEW

**Review by SpecialAro — APPROVED** [review]
Everything looks fine! Thank you!

**Comment by mcmxcdev** [comment]
> Everything looks fine! Thank you!

Does zoom in and out still work?

**Comment by SpecialAro** [comment]
> > Everything looks fine! Thank you!
> 
> Does zoom in and out still work?

Yes, but still doesn't persist when changing webviews. For that we will need to wait for 29.

**Comment by mcmxcdev** [comment]
> > > Everything looks fine! Thank you!
> > 
> > 
> > Does zoom in and out still work?
> 
> Yes, but still doesn't persist when changing webviews. For that we will need to wait for 29.

SGTM, lets get it merged!

**Comment by SpecialAro** [comment]
@all-contributors please add @xduugu for infra

**Pull request merged**
