### PR TITLE
Add a custom 'About' dialog - so that we can select & copy the text in linux

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

Use a custom modal dialog box for the `About` dialog - common for all OSes (not the electron default one)

#### Motivation and Context

Linux users should be able to select & copy the text in the `About` Dialog.

#### Notes
I am not sure which is better: 
1. The old one (on mac) is not modal, while the new one is modal.
2. The old one had a titlebar with the 3 buttons in any macos window - but, maybe this is a side-effect of the first point.
3. The old one can be closed with the `Esc` key, while the new one does not respond to `Esc` keystroke. If we need to support this, then we will need to attach a keyhandler to accomplish this?

#### Screenshots

These are the screenshots of the `About` dialog in macos:
Old:
Screenshot 2022-05-08 at 3 25 01 PM
New:
Screenshot 2022-05-08 at 3 24 05 PM

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by SpecialAro — COMMENTED** [review]
LGTM so far, but is still missing the Copy button, correct? I can try to take a look at this tomorrow.

Also, tested on Linux (Ubuntu) and it is still unable to select the text
image

Also, in Windows, I'm not able to select as well - but I couldn't previously neither.

**Comment by vraravam** [comment]
thanks for testing this @SpecialAro 
oops - if this doesn't work on windows and linux, then the PR is useless.

**Comment by mydarkstar** [comment]
@vraravam: I believe @SpecialAro is referring to commenting in those lines:
https://github.com/ferdium/ferdium-app/pull/121/commits/84f6fae03c2f8215123376e83f4d5f008bfd1456#diff-b4f429eea31e8320d58053dd092093dc7517378f13dd432a3099ac36e0f0b55dR752-R757

> still missing the **Copy button**

**Comment by vraravam** [comment]
> @vraravam: I believe @SpecialAro is referring to commenting in those lines: [84f6fae#diff-b4f429eea31e8320d58053dd092093dc7517378f13dd432a3099ac36e0f0b55dR752-R757](https://github.com/ferdium/ferdium-app/commit/84f6fae03c2f8215123376e83f4d5f008bfd1456#diff-b4f429eea31e8320d58053dd092093dc7517378f13dd432a3099ac36e0f0b55dR752-R757)
> 
> > still missing the **Copy button**

yes - that's a known item. I was mainly aiming for selection using mouse  + copy in all 3 OSes. I do not know how to add a button listener in the API that electron exposes for the "copy to clipboard" event trigger

**Comment by kris7t** [comment]
btw, for me, text is selectable in the native electron about box (`app.showAboutPanel()`) in linux both under X11 and wayland (sway)

**Comment by vraravam** [comment]
Closing this PR since its not useful.

**Pull request closed without merging**
