### PR TITLE
Shorten desktop entry comment field

### LINKED ISSUE #21: .desktop file Comment is too long and has parts that isn't relevant to the flatpak version
Screenshot_20230323-06

<details><summary>.desktop file</summary><p>

```
[Desktop Entry]
Categories=Network;InstantMessaging;
Comment=Ferdium is your messaging app / former heir to the throne of Austria-Hungary and combines chat & messaging services into one application. Ferdium currently supports Slack, WhatsApp, Gmail, Facebook Messenger, Telegram, Google Hangouts, GroupMe, Skype and many more. You can download Ferdium for free for Mac, Windows, and Linux. For enabling webcam access you need to connect "camera" plug to snap, and for microphone with PulseAudio - "audio-record" plug. This can be done in Snap GUI or via command: `snap connect ferdium:camera; snap connect ferdium:audio-record`.
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=ferdium --file-forwarding org.ferdium.Ferdium @@u %U @@
Icon=org.ferdium.Ferdium
MimeType=x-scheme-handler/ferdium;
Name=Ferdium
StartupWMClass=Ferdium
Terminal=false
Type=Application
X-Desktop-File-Install-Version=0.26
X-Flatpak=org.ferdium.Ferdium
X-Flatpak-RenamedFrom=ferdium.desktop;
```

</p></details>

It's too long, it even stretches the KDE application menu editor beyond the monitor. I think something shorter like `Ferdium is your messaging app that combines chat & messaging services into one application.` would be better.

At the very least, the snap part makes no sense, and if the Flatpak equivalent is to be added, it should be kept to the flathub page description (like Steam does) instead of the .desktop file.

### LINKED ISSUE #1079: Bug: overly verbose and inappropriate Comment in installed .desktop file
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu Mate 22.04.2

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

After installing from github latest release .deb via `deb-get` the DE Menu item (classic and Brisk) on hover should display a minimal informative comment or nothing

### Actual Behavior

The ferdium menu item shows a huge tool-tip on hover (from the .desktop file comment ? - nothing else shows the Comment though ...), including blurb that it can be downloaded for free ( I know, I just did and even installed it!) , that it supports lots of platforms (but I only care at this moment that it supports the one I'm running, and since it is in the menus now I hope that is the case), and that I need to fix up some snap permissions for audio etc - except it is not the snap but the deb so is not confined ....

Please could you provide appropriate Comment= text for the .desktop file (and whatever else is needed) depending on whether the app has been installed via apt / dpkg from a .deb or using the snap

### Steps to reproduce

Install the latest 6.2.4 release .deb  from github on  ubuntu-mate
search ferdium in the brisk or classic menu
hover over the Ferdium desktop entry

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by deadmeu**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Shortens the desktop entry comment to a more reasonable length.

#### Motivation and Context

The current desktop entry is too long and can not be read properly in standard app launchers. This change closes https://github.com/flathub/org.ferdium.Ferdium/issues/21

#### Checklist

- [x] My pull request is properly named

#### Release Notes

Shorten desktop entry comment field

### CODE REVIEW

**Review by vraravam — APPROVED** [review]

**Comment by marie-bnl** [comment]
I find the wording a bit strange. Overall I don’t think “combiner” is an appropriate term. Here is what I came across when looking for its meaning:

image

**Comment by deadmeu** [comment]
The current phrasing commonly used with Franz/Ferdium/Rambox revolves around how the program "combines" messaging services and web applications. Combiner just means the program is a thing that combines things together.

I took inspiration from some programs like Firefox, LibreOffice, and VSCode, which use these types of task based nouns in their descriptions:
- Firefox/Brave: Web **browser**
- LibreOffice Writer: Word **Processor**
- Code: Text **Editor**

However, these programs have very short and concise descriptions which isn't quite the case with my change, so maybe something better would be more along the lines of "Combines messaging services and web applications".

@vraravam do you have any preferences?

**Comment by marie-bnl** [comment]
I get your point, but “browser”, “processor” and “editor” are actual english words. And I can’t find any evidence that “combiner” is one, or at least one which means what we use it for here. And if it is, it seems to be pretty rarely used. But again I’m not a native english speaker so I might be wrong.

**Comment by kris7t** [comment]
_Combiner_ might be a perfectly [cromulent](https://en.wiktionary.org/wiki/cromulent) English word, but I don't think that's what Ferdium does. If Ferdium were indeed a _combiner_, it would be a tool produce _combined_ web applications from other. But Ferdium doesn't produce any new applications; it is merely a browser (or a messenger, to be more precise) that displays a _combination_ of web pages. That is, we (Ferdium developers) are doing the _combining_, not Ferdium itself. :smile:

**Comment by deadmeu** [comment]
> I get your point, but “browser”, “processor” and “editor” are actual english words. And I can’t find any evidence that “combiner” is one, or at least one which means what we use it for here. And if it is, it seems to be pretty rarely used. But again I’m not a native english speaker so I might be wrong.

You might be right. It's more informal and kind of just felt right at the time I wrote it. A more real term would be something like *aggregator*.

**Comment by marie-bnl** [comment]
Aggregator seems just fine to me

**Comment by Alphrag** [comment]
I fully agree for the mention of `aggregator` instead of `combiner`. 
Also, I think it is useful to have 2-3 quick examples in the description (like @victorbnl suggested in #1122), by removing the fact that it is a general web app (even though it is true) to keep it short as the latter is less important in my opinion.

**Comment by deadmeu** [comment]
> I fully agree for the mention of `aggregator` instead of `combiner`. Also, I think it is useful to have 2-3 quick examples in the description (like @victorbnl suggested in #1122), by removing the fact that it is a general web app (even though it is true) to keep it short as the latter is less important in my opinion.

I have a couple of concerns about this:
1. I'm slightly worried that _aggregator_ might be too complex of a word and might not be accessible enough.
2. I don't think other products or services should be referenced since Ferdium is not related to them in any way. These examples work great for the project's description in the README file and on app stores but once the user installs Ferdium they shouldn't need to read these examples every time they open their application launchers.

I still think I'm leaning more towards my earlier example of "Combines messaging services and web applications" but if the consensus is that _aggregator_ is fine to use then I could update the text to "General web application and messaging services aggregator" and we could just go with that :slightly_smiling_face:.

**Comment by Alphrag** [comment]
> I still think I'm leaning more towards my earlier example of "Combines messaging services and web applications" but if the consensus is that _aggregator_ is fine to use then I could update the text to "General web application and messaging services aggregator" and we could just go with that slightly_smiling_face.

Ok, I see your point. Then what do you think of avoiding both problems by putting something like "Web app bringing all your messaging services in one place"? 

Also since the description contains important elements for snap, it would be good to move it to the settings specific for that target (line 10-14), so that users will see this information when downloading from the store.

**Comment by vraravam** [comment]
I like this suggestion: "Web app bringing all your messaging services in one place"
or we could also go with "Desktop app bringing all your messaging services into one installable"

**Review by vraravam — APPROVED** [review]

**Comment by vraravam** [comment]
@all-contributors please add @deadmeu for code

**Pull request merged**
