### PR TITLE
fix: dont replace custom icon when service updates

### PR DESCRIPTION
**Pull request by cino**
- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
- Removed unused property which could create confusion
- Modified if check to look at the correct property to indicate if there is a custom icon set for the service.

#### Motivation and Context
#336 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Fixed function that checks if the icon needed to be replaced.

### CODE REVIEW

**Review by SpecialAro — CHANGES_REQUESTED** [review]
Is the recipes submodule update needed for this PR?

If not, please remove it.

**Review by SpecialAro — APPROVED** [review]

**Comment by cino** [comment]
@vraravam Thanks for solving that.

Let me check one thing in this PR before merging tho I've seem to introduced a bug which needs to be resolved first :)

**Comment by cino** [comment]
Now it's properly working.

**Review by vraravam — APPROVED** [review]
I haven't tested this locally. Assuming that you have already tested this.

**Pull request merged**
