### PR TITLE
Remove arm build for mac

### PR DESCRIPTION
**Pull request by Alphrag**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Temporarily remove the building of arm assets for Mac.

#### Motivation and Context

An issue with arm builds on Mac recently (see #1360) has meant that we have had to remove 
assets in the recent updates for this operating system in order to avoid breaking it for users. This PR temporarily disable building arm versions of the releases for Mac until the problem is identified and fixed (the x64 version should work fine on these computers in the meantime).

#### Checklist

- [x] My pull request is properly named
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by SpecialAro** [comment]
I think windows is also failing

**Comment by SpecialAro** [comment]
image

This is a screenshot by @bkimmett on arm windows

**Comment by Alphrag** [comment]
Oh, so shall we remove arm builds from all OSes then?

**Comment by SpecialAro** [comment]
> Oh, so shall we remove arm builds from all OSes then?

I think that might be the best approach...

**Comment by mcmxcdev** [comment]
That locks out various users from using Ferdium, huge breaking change :/ 

Do we have any clue what the issue is? Did it ever work? Reinstating that arm support after merging this should be high priority.

**Comment by SpecialAro** [comment]
> That locks out various users from using Ferdium, huge breaking change :/
> 
> Do we have any clue what the issue is? Did it ever work? Reinstating that arm support after merging this should be high priority.

I cannot confirm if this ever worked before... But, at least, there are users using it on macOS that reported that the builds broke on a nightly (after reverting the nightly it still continues to break)...

**Comment by bkimmett** [comment]
I think someone said it's the sqlite3 component not having proper bindings: https://github.com/ferdium/ferdium-app/issues/1360#issuecomment-1752165977

Can confirm that the x64 nightly build works on macOS ARM via Rosetta, btw.

**Comment by ylluminate** [comment]
I will be holding off on using any new versions of Ferdium then as I use a lot of services and using it via Rosetta is not an option for me (and several people I know). 

Please let us know when we can get back on the arm64 train again.

**Comment by SpecialAro** [comment]
Closing in favor of https://github.com/ferdium/ferdium-app/pull/1400

**Pull request closed without merging**
