### PR TITLE
Reverts commit that causes the problem of not being able saving service

### LINKED ISSUE #167: Bug:  Unable to save service (Nightly 38)
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.38

### What Operating System are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.37

### Expected Behavior

Service saves and adds

### Actual Behavior

After clicking "Save service" nothing happens (no output in terminal as well)

### Steps to reproduce

1. Delete config foolder (~/.config/ferdium)
2. Launch Nightly 38 (appimage)
3. "Use Ferdium without an Account"
4. Try to add/save any service
5. Repeat steps with Nightly 37 to make sure saving works there

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
This reverts commit bbde4a9d54d9c7dc03f34ca4113061a605dd5040.

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Reverts commit that causes the problem of not being able saving service

#### Motivation and Context
Fixes #167  by reverting the commit that caused the problem.
I've bisected and this (bbde4a9d54d9c7dc03f34ca4113061a605dd5040) is the commit to blame for the issue.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
Wasn't there a way to find the solution other than reverting @SpecialAro ?

**Review by vraravam — APPROVED** [review]
LGTM - I will also create and release another nightly to fix the issue

**Comment by SpecialAro** [comment]
> Wasn't there a way to find the solution other than reverting @SpecialAro ?

Yes! I thought that we should cherrypick this commit and try again, but only merge it when this is fixed, if you agree.

I raised this PR only because this is a major issue that breaks usability (mostly for new users).

Also, this broke the "Save Service" button location (before on the right, now on the left), so maybe several buttons are facing issues such as this one's or possibly worst ones.

**Comment by vraravam** [comment]
yes - and i had the same thought - that this PR needs merging , and an out-of-band nightly created. I have already triggered the GH workflow for a new nightly

**Pull request merged**
