### PR TITLE
Upgrade electron to '29.0.0'

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Upgrade electron to stable version

#### Motivation and Context

[Changelog](https://github.com/electron/electron/releases/tag/v29.0.0)

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by SpecialAro — APPROVED** [review]
Should we trigger a stable Ferdium release ? 😁

**Comment by vraravam** [comment]
> Should we trigger a stable Ferdium release ? 😁

yes, that's the intent (but after 1 nightly where the wider group of beta testers can also chime in with their experience)

**Comment by marrws** [comment]
According to the Release Notes[^1], the fix has been backported to 27 and 28 too in case you don't want to early adopt 29

> Fixed an issue where zoom level settings did not persist per-session for webviews. https://github.com/electron/electron/pull/40650 (Also in https://github.com/electron/electron/pull/41269, https://github.com/electron/electron/pull/41268)
[^1]: https://github.com/electron/electron/releases/tag/v29.0.0

**Comment by vraravam** [comment]
> According to the Release Notes[1](#user-content-fn-1-4d3ddec2ef65cecf1b8bbdc0e0a3cc12), the fix has been backported to 27 and 28 too in case you don't want to early adopt 29
> 
> > Fixed an issue where zoom level settings did not persist per-session for webviews. [electron/electron#40650](https://github.com/electron/electron/pull/40650) (Also in [electron/electron#41269](https://github.com/electron/electron/pull/41269), [electron/electron#41268](https://github.com/electron/electron/pull/41268))
> 
> ## Footnotes
> 1. https://github.com/electron/electron/releases/tag/v29.0.0 [↩](#user-content-fnref-1-4d3ddec2ef65cecf1b8bbdc0e0a3cc12)

Its been backported, but not yet released. Instead, we chose to upgrade to the latest stable. In our internal testing on Windows, linux an macos, things are working fine.

**Pull request merged**
