### PR TITLE
update react-router-dom,react-tooltip& react-transition-group

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Update react-router-dom, react-tooltip & react-transition-group latest version

#### Motivation and Context

update package to latest version

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

- React Router dom updated via legacy solution, further update to node module react-router-dom may need rewrite of router workflow
 - applied solution credits: https://github.com/remix-run/react-router/issues/9630#issuecomment-1341643731
 - recommend solution ref: https://github.com/remix-run/react-router/issues/9422#issuecomment-1302564759

### CODE REVIEW

**Comment by ghost** [comment]
@Alphrag - Have fixed the update issue. Kindly verify in windows build, if all issue are resolved.
@vraravam - kindly verify once (I have also verified it already)

This time let us merge this pr after testing a while in windows

**Comment by Alphrag** [comment]
That's great thank you 😃 I can confirm that the last changes you've added have indeed fixed the problem both for the recipe reload and the software update banner. So all good on windows this time!
I have also tested it on my mac x64 and everything is working as expected there as well.

**Review by Alphrag — APPROVED** [review]

**Review by vraravam — APPROVED** [review]
Tested the normal working of Ferdium on a mac m1 machine. Haven't tested recipe or app upgrades.

**Comment by ghost** [comment]
Added windows test image(credits: @Alphrag )
Capture-2023-07-23-114729

Added Mac M1 test image
Capture-2023-07-23-114730


Team, if any one tested app in other OS kindly attach your screenshots.

**Comment by Alphrag** [comment]
Tested also on the appImage on Linux. So we are good to go!

image

**Pull request merged**
