### PR TITLE
update react-router-dom,react-tooltip& react-transition-group

### PR DESCRIPTION
**Pull request by ghost**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Update react-router-dom, react-tooltip & react-transition-group latest version

#### Motivation and Context

update package to latest version

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

- React Router dom updated via legacy solution, further update to node module react-router-dom may need rewrite of router workflow
 - applied solution credits: https://github.com/remix-run/react-router/issues/9630#issuecomment-1341643731
 - recommend solution ref: https://github.com/remix-run/react-router/issues/9422#issuecomment-1302564759

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
Works fine on m1 mac. (Haven't tried teams meeting and screen sharing in any of the configured apps). LGTM

**Comment by vraravam** [comment]
@Alphrag - have you been able to test this on windows? Could anyone else also do the same please? Its been sitting for quite some time now

**Comment by vraravam** [comment]
I accidentally merged this into the develop branch. (Was trying to rebase from develop for latest changes - so that testing can be done with the latest).
@Alphrag / @SpecialAro - please can one of you confirm if this works on windows today? Else, we will have to revert this commit

**Comment by SpecialAro** [comment]
Hey @vraravam 😄 

I tested on my windows today and it was working properly!

**Comment by Alphrag** [comment]
@vraravam Nope, there is still the same error that happens when the update bar should appear, as can be seen below... 
The only way to test this problem is to actually build and install the app but setting the version in `package.json` lower than the latest available release, so that it actually tries to upgrade (in debug mode update is disabled so this behavior can't be seen).  I haven't checked if on mac, that also produces the same thing, but I've attached the lof of the errors that appear in the console when this happens.
 
ws_error_mobxreact

[error-module-react.txt](https://github.com/ferdium/ferdium-app/files/12114436/error-module-react.txt)

**Comment by ghost** [comment]
@Alphrag That's helpful, Will resolve it :)

**Comment by ghost** [comment]
@Alphrag , I tried to replicate failure in mac m1 but it didn't work.
steps:
1. reduce package.json > version by 1 minor 
2. build the app and install in mac
3. it having some error when i try to check for update from settings

can you help me with this ? or this issue only occure in windows?

**Comment by Alphrag** [comment]
> can you help me with this ? or this issue only occure in windows?

Answering simply for completeness here: the issue also occurred on Mac, and I was able to reproduce it. However, to make the update banner appear, the app must be built without the `--dir` option currently present in the `build-unix.sh` script usually used (with the option the app does not include the file allowing to check for updates). Then having `Enable updates` toggle will allow the banner to appear if a service is outdated by prompting the reload. 
But this is still not enough for the app update banner. Indeed, it only appears when an update is available, has been downloaded and verified for compatibility. Thus, the app must have been signed during the build with the same key as the one from the incoming update, which reduces even more the testing possibilities for this particular event since one needs to have the code signing certificate installed on their computer.

**Pull request merged**
