### PR TITLE
Turn off usage of 'debug' npm package using with electron-16+

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)

5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

As discussed in #17, temporarily turning off debugging using the 'debug' npm module.
Please note that I have not trimmed this list of files - they all seem logically connected - and when I turned off and restart Ferdium - my discord was still working!

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
This is way too extreme, I think. We don't have to remove all uses of `debug`, only those that run in the `preload` script of our `webview`. Of course, figuring out which of the usages are they is a bit difficult, because main/renderer/preload scripts aren't kept separate in the ferdium codebase, unfortunately.

**Comment by vraravam** [comment]
yes, unfortunately, there's no other way I could think of. As soon as file `A` imports file `B`, if the `require('debug')` is evaluated in file `B`, then we have the same problem, isn't it?

**Comment by kris7t** [comment]
We could try to create a shim which we import everywhere instead of `debug`, that check whether we're in the preload environment and only requires `debug` if we aren't (it can just return the `console.log` method in the preload, for example). This we at least have debugging support in the rest of the app.

Something like

```javascript
export default function debug(namespace) {
  if (globalThis.ferdiumPreload) {
    return console.log;
  }
  return require('debug')(namespace);
}
```

saved as `preloadSafeDebug.js`, and then replace each use of `require('debug')` with `require('../preloadSafeDebug')` or something like that. Then `webview.js` could set `globalThis.ferdiumPreload = true;` to avoid pulling in `debug`.

But this is a pretty rough idea, and I'll have to try it to see whether it works.

**Comment by vraravam** [comment]
I thought about this - but, im not enough of a js dev to have implemented this.

**Comment by kris7t** [comment]
I'll try to do the alternative fix on top of a _revert_ of this. Thus, we can push out a working nightly now, and get back debugging support later

**Review by kris7t — APPROVED** [review]

**Comment by mydarkstar** [comment]
@kris7t I like the shim idea!
It could also use some currying to display the namespace for each `console.log` call, along the lines of:
```js
return (...params) => console.log(`[${namespace}]`, ...params);
```

Also, just as a side note. I'm not entirely sure how Node implements this, but could there be a performance issue with calling `require` on every function call?

**Comment by kris7t** [comment]
We'd only call `require` on each `debug` function call, but that's usually only called once per module (to initialize a new logger for the namespace), so I wouldn't be too afraid of it.

Adding the prefix is a nice idea!

**Comment by dqos** [comment]
This looks good to me, can we proceed with merging? Then we can roll out nightly.8 asap.

**Pull request merged**
