### PR TITLE
Feature: Add ability to navigate recipe with mouse buttons

### LINKED ISSUE #45: Feature: direct mouse buttons 4 & 5 to the web app
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have one of those gamer mouse that has 2 extra buttons at the side, where one goes forward in history and the other goes backwards, but in ferdium those buttons are detected by the UI, so when I try to go backwards on reddit it shows the previous ferdium menu screen.

### Proposed Solution

Redirect the mouse buttons 4 & 5 to the webapp instead of ferdium UI.

### Alternatives Considered

I've seen that there is options to use ctrl+arrow to go back and forth, and there is also the right click menu, but I'm already hard wired to just click the mouse button to go back right away. I can survive with that at least.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Feature: Add ability to navigate recipe with mouse buttons

#### Motivation and Context
This feature adds the ability to navigate recipes with mouse buttons. It fixes #45.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Feature: Add ability to navigate recipe with mouse buttons

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
I haven't tested this since I dont use a mouse. but, the changes look correct.

**Comment by SpecialAro** [comment]
> I haven't tested this since I dont use a mouse. but, the changes look correct.

I've tested locally and seems to be fine 😄 I'll wait for the builds to pass so we can merge.

**Comment by kris7t** [comment]
Ah, so it's a `mouseup` event and not an `auxclick` event :slightly_smiling_face: no wonder why I didn't manage to fix this, I was trying to hook the wrong event

**Comment by SpecialAro** [comment]
> Ah, so it's a `mouseup` event and not an `auxclick` event 🙂 no wonder why I didn't manage to fix this, I was trying to hook the wrong event

Yep! I was doing the same for some days now 😭 Took a lot of reading to achieve this (which was pretty simple in fact). For reference, https://github.com/electron/electron/issues/17134 this is currently still open and I confirmed that 'app-command' doesn't trigger mouse events properly.

**Comment by pepper3k** [comment]
@SpecialAro Thank you! I was missing this badly! 

I really appreciate it!

**Comment by SpecialAro** [comment]
@eitanprezes 😅 me too! Thank you for your feedback. Did you manage to test it yet? The latest nightly (57) is failing for quite some people and we are still looking why.

**Comment by pepper3k** [comment]
Just tested it on multiple services, including gmail, outlook365, tutanota, protonmail, github, and so far works like a charm.
Win7x64 - nightly-56
nightly-57 was giving me a blank screen too :(
Thanks again!

**Comment by kris7t** [comment]
nightly.58 should have fixed the blank screen bug now

**Comment by pepper3k** [comment]
@kris7t Confirmed, this is fixed!

**Pull request merged**
