### PR TITLE
Downgraded 'node' to '16.14.2'

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)

5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

Downgrade `node` to `16.14.2` (LTS).

#### Motivation and Context

According to https://githubmemory.com/repo/electron/electron/issues/32114 and other bug tickets, node 18 has problems with `node-gyp`. This is precluding us from proceeding with #26 for faster/cleaner builds.

I have tested this on mac - both x64 and arm. Need some others to test this on linux and win10 + win11

Confirmed to work with
- [x] mac (x64)
- [x] mac (arm)
- [x] linux
- [x] win 10
- [x] win 11

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by nathanaelhoun — APPROVED** [review]
I can confirm it works on Linux x64
image

**Comment by SpecialAro** [comment]
Tried with windows 11 and it failed executing npm i. I can post the printscreen later on

**Comment by Alphrag** [comment]
Can confirm on Windows 10: with SDK Windows10 v10.0.19041.0 and MSVC v143 (VS 2022)
w10_node16_info

**Comment by SpecialAro** [comment]
I have it working on Windows 11 but only with Windows 10 SDK selected. Please, be aware of this - might be a requirement (Further test is needed on this). This PR is not affected if the correct SDK is selected.

**Pull request merged**
