### PR TITLE
chore: Upgrade 'electron' to v27.0.1

### PR DESCRIPTION
**Pull request by Alphrag**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Upgrade `electron` to `v27.0.1`.

#### Motivation and Context

This upgrade brings a more up-to-date chromium version, as well as some security fixes.

#### Screenshots

Capture d’écran 2023-10-19 à 00 58 18

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

chore: Upgrade `electron` to `v27.0.1`

### CODE REVIEW

**Review by SpecialAro — APPROVED** [review]
LGTM if the builds pass 😁

**Comment by mcmxcdev** [comment]
Funny, I was planning on doing that upgrade tomorrow, you guys were faster ;)

Someone with Linux should verify if this version works, because v26 was breaking for me on Ubuntu. Can't get to testing it until tomorrow unfortunately.

**Comment by Alphrag** [comment]
image

@mcmxcdev All good for me on running the AppImage on my Ubuntu 20.04 (using my fork build) :wink:

**Comment by mcmxcdev** [comment]
Yup, works for me too, ready to merge!

image

**Pull request merged**
