### PR TITLE
fix: add Crowdin languages mapping in config file

### PR DESCRIPTION
**Pull request by andrii-bodnar**
Hey everyone,

just noticed there are some language codes in the project that have locale code instead of two letters code. Crowdin has a feature to map these codes.

Also, I've noticed that there a some duplicated languages in the locales folder - zh and zh-Hans, zh-Hant and zh-TW. I guess some of these languages are excessive here but not sure which. @nathanaelhoun could you please point out what codes are unneeded here? I will remove them also and will update the mapping if needed

#185

### CODE REVIEW

**Comment by vraravam** [comment]
@nathanaelhoun - would you be able to verify and approve this change? IF so, we can then merge it in?

**Comment by nathanaelhoun** [comment]
Hi @andrii-bodnar, thanks for taking a look, and sorry for the delay in my response!

Your comment about duplicated languages is correct. Some of them as excessive, but unfortunately, I do not know chinese well and I couldn't tell which one are duplicates. Do you know?

**Review by nathanaelhoun — APPROVED** [review]
Otherwise, these changes are looking good to me!

**Comment by andrii-bodnar** [comment]
@nathanaelhoun the same, also not sure which of these files are excessive 😬

**Comment by nathanaelhoun** [comment]
I'll just merge this one after the checks pass, and we will clear up the maybe excessive languages in another PR. Thanks @andrii-bodnar!

**Pull request merged**
