### PR TITLE
Switch npm to pnpm

### PR DESCRIPTION
**Pull request by balajiv113**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

Move electron-builder outside of package.json script. As using inside is causing trouble in native buildings. The same model we already followed to fix windows building with pnpm

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Testing
I have done testing on macOS

**Steps to test**
- Remove `--$TARGET_ARCH --$TARGET_OS --dir` from the build scripts
- Run CLEAN=true ./scripts/build-unix.sh
- Once done, copy arm Ferdi.app to M1 machine and verify if no error thrown in console and vice versa (Build in arm and copy amd Ferdi.app to intel and verify no errors thrown)

### CODE REVIEW

**Comment by balajiv113** [comment]
**electron-builder.npmrc tweaks**

This file contains tweaks required to run electron-builder with pnpm mentioned here https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422
**Note** electron-builder.npmrc will be renamed to .npmrc and move inside build folder for electron-builder build phase

**Issues after adding tweaks**
1. Windows github action build issue (Not a valid 32bit application), related to https://github.com/electron-userland/electron-builder/issues/6933. 
**Note:** Current tweak of running `pnpm electron-builder` directly (not using package.json scripts) is wrong. With this electron-builder is using npm and not pnpm
2. Pnpm not rebuilding native binaries, related to https://github.com/pnpm/pnpm/issues/5560

**Core issue**
Above tweaks will not needed if this issue is fixed https://github.com/develar/app-builder/issues/84

**Tests to be done**
The below check should be done when migrating to pnpm again

- [x] local & github actions builds are fine on all OS & platform
- [x] Cross platfrom checks for macOS - Build both binaries (amd64 & arm64) on intel machine and see if arm64 binaries are running fine on mac M1 and vice versa

**Comment by BalajiVijayakumar1195** [comment]
Moving back to draft :) As it is again blocked.

**Comment by balajiv113** [comment]
Moving back to draft :) As it is again blocked

**Comment by balajiv113** [comment]
Added yet another small tweak to get around the blocker.

**Review by SpecialAro — APPROVED** [review]
I wasn't able to build this PR locally because it was throwing some errors related with MSVS Tools (I tested 2022, 2019 and 2017 with no success - it doesn't fail for my arch x64, but fails for the others).

Nevertheless, as the CI didn't fail for Windows, I vote for we to move to merge this PR.

Thank you @balajiv113 for not giving up on this conversion 😄

**Comment by Alphrag** [comment]
Tested to build on my windows 10 x64 and the builds for all architecture work exactly as expected! Well done @balajiv113 for that work 🤩 🎉 

pnpm_build_pass

**Review by Alphrag — APPROVED** [review]

**Pull request merged**
