### PR TITLE
Upgrade electron to '29.0.0-beta.8'

### LINKED ISSUE #1419: Zoom resets after service change
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.3-nightly.4

### What Operating System are you using?

Windows

### Operating System Version

Win10

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

After changing between services the zoom state for service is saved

### Actual Behavior

After changing between services the zoom is reset

### Steps to reproduce

1. Open service 1
2. Change zoom for service 1
3. Change to service 2
4. Return to service 1

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_Update (27.10.23):_
Build info
```
Version: 6.6.1-nightly.1
Server: Ferdium Server
Electron: 27.0.1
Chrome: 118.0.5993.89
Node.js: 18.17.1
Platform: Windows 10
Arch: x64
Build date: Fri Oct 27 2023 03:39:52 GMT+0300 (Eastern European Summer Time)
Git SHA: 65d24965
Git branch: nightly
```

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Upgrade to Electron v29

#### Motivation and Context
This is a WIP PR to prepare ourselves to upgrade to Electron v29. Currently v29 is on beta (v29.0.0-beta.5) - a full release should be out at February 20.

This PR fixes https://github.com/ferdium/ferdium-app/issues/1419

Tested in:
- [x] Windows
- [x] Linux
- [x] MacOS

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Upgrade electron to '29.0.0-beta.5'

### CODE REVIEW

**Comment by SpecialAro** [comment]
@mcmxcdev and @vraravam should we merge this Electron beta version to the nightly builds to prepare for the full release in February 20 ?

This way we could push a stable release as fast as possible so that users that were affected by https://github.com/ferdium/ferdium-app/issues/1419 could get a stable version faster.

**Comment by mcmxcdev** [comment]
> @mcmxcdev and @vraravam should we merge this Electron beta version to the nightly builds to prepare for the full release in February 20 ?
> 
> This way we could push a stable release as fast as possible so that users that were affected by #1419 could get a stable version faster.

I am definitely in favor of this. Not too scared about it being a beta release (although Electron has a history of breaking things).

**Comment by vraravam** [comment]
previously, when i was doing the same - it was not appreciated.

My intention even then (and now) was to raise it as draft PRs and request the active contributors to build locally from source and test it out. I would suggest/vote for the same even now. ie do not merge into master, broadcast to all active contributors to checkout this branch and build from source code with the provided scripts, and run the app to verify functionality

**Comment by mcmxcdev** [comment]
You are always appreciated Vijay!

I would prefer to wait until a new major release matures and puts out patches first, but this zoom issue is a big problem for a lot of users,  and we have let them wait a long time already.

I am on a business trip currently but I might be able to run it locally today and provide feedback!

**Comment by mcmxcdev** [comment]
Just tested it on Ubuntu 23.10 and it works great!

Zoom out doesn't work, only zoom in and reset zoom to default level, BUT that was already an issue like a year ago and is tracked on Electron somewhere iirc.

**Comment by SpecialAro** [comment]
> Just tested it on Ubuntu 23.10 and it works great!
> 
> Zoom out doesn't work, only zoom in and reset zoom to default level, BUT that was already an issue like a year ago and is tracked on Electron somewhere iirc.

Nice! I'll mark it as checked and I'm testing now in macOS.

> My intention even then (and now) was to raise it as draft PRs and request the active contributors to build locally from source and test it out. I would suggest/vote for the same even now. ie do not merge into master, broadcast to all active contributors to checkout this branch and build from source code with the provided scripts, and run the app to verify functionality

I agree with this as well. I'm testing myself on Windows and macOS but it would be good if other people test it as well.

Also, for the future, do you think it could be worth it to have some way to store the "builds" triggered by PRs? This way, users/maintainers could test versions way faster (downloading and running the packed app). I can try to investigate this further if you think it might be worth it!

**Comment by SpecialAro** [comment]
Just tested on macOS and everything seems to be fine. I'll ping other contributors to test this PR on their systems as well just to be sure.

**Comment by vraravam** [comment]
> do you think it could be worth it to have some way to store the "builds" triggered by PRs? This way, users/maintainers could test versions way faster (downloading and running the packed app). I can try to investigate this further if you think it might be worth it!

Unfortunately, (based on past investigations), this is not possible using the "GH Releases" feature. We would have to  merge to the develop branch, which will then trigger the nightly build, and only then will the Draft artefacts be created. (Draft is before any kind of publishing - whether its for nightly, beta or public/stable builds). AND, these "Draft" artefacts will not be available for any contributors that are not specifically approved in the Github org space. (I dont know whether "outside collaborator" will have this access either).

Which is why the "build from source" seems the simplest option as of now. If they are a code contributor, they must surely have the ability to build from source and run it locally. If so, then as core contributors, its our responsibility to ensure that the `./scripts/build-<OS>.sh` scripts are maintained to work as expected.

**Comment by vraravam** [comment]
Tested the following functionalities on macos Sonoma 14.4 beta (on m2 mac):
1. Opening with a pre-existing profile
2. Older recipes were auto-updated as expected
3. Switching between services using keyboard shortcuts
4. Switching between workspaces using keyboard shortcuts
5. Haven't tried updating the main app (don't have cert-signed for local build)
6. Haven't tried audio/video calling in any service (jitsi, meet, discord are the services that i have configured which have such a feature)

**Comment by Alphrag** [comment]
To add to @vraravam's tests, I tried this PR on Windows 10 x64, MacOS Big Sur x64 as well as Fedora 34 x64, and can confirm that all of the following works as expected:
- zooming in and out, and resetting zoom with either shortcuts or menu items (cf video below);
- video calls (I tried with element);
- auto-updating for both Windows and MacOS;
- adding and deleting recipes.

So it seems quite good on my end for when the stable release of electron `v29` will land.

https://github.com/ferdium/ferdium-app/assets/34252790/eb724586-d374-4814-b92f-f1bdb76293c5

**Comment by SpecialAro** [comment]
Great 😁 thank you all for taking the time to test it! let's move to merge then?

**Pull request merged**
