### PR TITLE
Revert "feat: add deeplink to service (#1344)"

### PR DESCRIPTION
**Pull request by SpecialAro**
This reverts commit 970738c953865b7346f5f85c576be2af2cdd7f2c.

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Motivation and Context
This PR reverts the the PR https://github.com/ferdium/ferdium-app/pull/1344 that introduced a new feature for the deeplink (that seems to be breaking in some macOS versions).
Therefore this re-opens https://github.com/ferdium/ferdium-app/issues/1243 and closes (after confirmation) https://github.com/ferdium/ferdium-app/issues/1360 and https://github.com/ferdium/ferdium-app/issues/1387

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by ylluminate** [comment]
@SpecialAro I can test a build very quickly if you have one to throw at me on arm64 macOS 14.1b1.

**Comment by Alphrag** [comment]
@ylluminate If you're happy with that, I have put a release on my repo that incorporate this PR in order to test it, and that uses the same github build process. It is there: https://github.com/Alphrag/ferdium-app/releases/tag/v6.5.1-fix.2.

Note: I purposefully made the assets different from the normal ferdium releases: the app is called `Ferdium-Alphrag` which means it will make a new folder of configuration under the same name next to the normal `Ferdium` folder so that it won't break any of your config (but will start completely empty). Let us know if that works for you.

**Comment by ylluminate** [comment]
@Alphrag it does start and new service load. I have NOT tried to restore services from Ferdium-proper to test that scenario out as I'm on the road and do not have time to research, but it seems promising.

**Comment by bkimmett** [comment]
It starts, and the "new service" window loads, but when I try to save a service that I've newly created, I click the button and nothing happens, except for some error logs:

Screen Shot 2023-10-04 at 9 10 48 AM

Screen Shot 2023-10-04 at 9 10 52 AM

**Comment by SpecialAro** [comment]
Ok, this issue is related with the communication with the internal server, so it seems


(I'm sorry but I'm currently in Cologne so my computer access is limited to try and fix this)

**Comment by SpecialAro** [comment]
Closing this as this is going to be fixed by https://github.com/ferdium/ferdium-app/pull/1400

**Pull request closed without merging**
