### PR TITLE
fix: update appearance/index.ts to apply the accent color on tabs

### PR DESCRIPTION
**Pull request by DenysMb**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

After this previous PR https://github.com/ferdium/ferdium-app/pull/1944, as stated by @wvds here https://github.com/ferdium/ferdium-app/pull/1944#issuecomment-2470225090, the accent color was not being updated in tabs. This happened because, with the change from `border` to `box-shadow`, I forgot to update the `appearance/index.ts`, where we do this change. It was still changing the `border-color`, but since there is no more `border`, it was doing nothing. I just needed to update the code there to use the `box-shadow`.

#### Motivation and Context

This is a bug.

#### Screenshots

image
image

#### Checklist

- [X] My pull request is properly named
- [X] The changes respect the code style of the project (`pnpm prepare-code`)
- [X] `pnpm test` passes
- [X] I tested/previewed my changes locally

#### Release Notes
Fix the problem that was causing the accent colors to not be applied to tabs indicator

### CODE REVIEW

**Comment by vraravam** [comment]
@DenysMb  - Thanks for creating the PR so quickly, but please create PRs using the latest commit from the `develop` branch. Otherwise, all testing (especially visual changes) will not be verifiable in the correct manner.
And, of course, the CI runs unnecessarily.

**Comment by DenysMb** [comment]
@vraravam Yeah, sorry. I forgot to fetch the changes before I made the changes.

**Comment by vraravam** [comment]
> @vraravam Yeah, sorry. I forgot to fetch the changes before I made the changes.

Please retest with the latest version since I have rebased from the latest develop. Once you do and confirm that the fix works, we can merge (after the CI run also completes successfully)

**Comment by DenysMb** [comment]
@vraravam Everything working fine here after the rebase.

**Review by vraravam — APPROVED** [review]
not tested by myself. OP says its working.

**Pull request merged**
