### PR TITLE
Add audio-record plug to snap build

### PR DESCRIPTION
**Pull request by NathanaelGandhi**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

- [x] #214 Add audio-record to [/electron-builder.yml](https://github.com/ferdium/ferdium-app/blob/356c87fb2e87c73161b7e41f21facc068e8dad88/electron-builder.yml) snap plugs
- [x] Update linux description from pulseaudio plug to audio-record plug

#### Motivation and Context

The audio-record interface should be implemented to allow the system audio service, such as PulseAudio, to enable microphone/audio recording hardware access (in Snap).
Ref: https://snapcraft.io/docs/audio-record-interface

This is preferred to implementing the depreciated plug PulseAudio directly, which is the currently recommended option by ferdium for snap users. 
Ref: https://snapcraft.io/docs/pulseaudio-interface

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (added in existing style of electron-builder.yml)
- I don't know how to test electron-builder changes locally

#### Release Notes

Add audio-record plug to snap build

### CODE REVIEW

**Comment by SpecialAro** [comment]
LGTM but can't test it locally.

**Review by vraravam — APPROVED** [review]
I haven't tested this locally since I dont use snap or linux. I assume this is valid. Approving.

**Comment by vraravam** [comment]
@NathanaelGandhi - do you think this is ready to be merged?

**Comment by NathanaelGandhi** [comment]
> @NathanaelGandhi - do you think this is ready to be merged?

@vraravam yes, this only adds the plug to the electron-builder in the same format as the existing plugs. As we have discussed earlier there isnt a way for me to test that this builds everything cleanly. I have checked the spacing of the added command to match existing.

**Pull request merged**
