### PR TITLE
Repair not working FAQ link

### PR DESCRIPTION
**Pull request by cm-schl**
old link pointed to a 404 site

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

simply removed a trailing slash to make the faq link work 😉

#### Checklist

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`npm run prepare-code`)
- [ ] `npm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Review by vraravam — APPROVED** [review]

**Comment by vraravam** [comment]
Thanks @cm-schl !

**Comment by vraravam** [comment]
@all-contributors please add @cm-schl for doc

**Comment by HenrijsS** [comment]
@vraravam Seems like this somehow popped back up.

**Comment by vraravam** [comment]
@HenrijsS - the `README.md` still has the above fix. Where do you see this reverting?

**Comment by vraravam** [comment]
@HenrijsS - the `README.md` still has the above fix. Where do you see this reverting?

**Comment by HenrijsS** [comment]
@vraravam When creating a new GitHub issue.
There's the last option to view the FAQ. 

There the last slash is throwing a 404.

(Seems like this was only in the Readme for the project)

**Comment by vraravam** [comment]
Thanks for pointing those out - I have now fixed them as well

**Pull request merged**
