### PR TITLE
Upgrade 'electron' to '26.1.0'

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [ ] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Upgrade electron to 26.1.0

#### Motivation and Context

[Changelog](https://github.com/electron/electron/releases/tag/v26.1.0)

#### Screenshots

Screenshot 2023-08-24 at 6 39 00 AM

#### Checklist

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`pnpm prepare-code`)
- [ ] `pnpm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by mcmxcdev** [comment]
Doesn't work properly on my end on Ubuntu. I see the Ferdium UI and then suddenly it starts blanking due to the `Error: sending from webFrameMain`:

Screenshot from 2023-08-24 07-26-16

I don't see any benefit in always being an early adopter of just recently released Electron versions. That time would be better invested in bug fixes/ features.

**Comment by kris7t** [comment]
@mcmxcdev The main problem is that [electron isn't really designed to be a browser](https://www.electronjs.org/docs/latest/tutorial/sandbox#a-note-on-rendering-untrusted-content), which has some [security implications](https://www.electronjs.org/docs/latest/tutorial/security#16-use-a-current-version-of-electron). In particular, electron aims to backport security fixes from chromium releases, but you have to keep in mind that the electron project in general has lesser resources than the chromium project.

The best bet for security is [staying on the latest chromium release](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#can-i-see-these-security-bugs-so-that-i-can-back_port-the-fixes-to-my-downstream-project), which generally means the latest electron release (the chromium release is freezed for a particular electron release, and security fixes are backported). This is quite annoying due to breaking changes in chromium, and generally wouldn't be needed if we didn't display remote untrusted content. For example, vscode or slack can afford to stay on older (but still supported) electron releases with backported fixes, because they don't generally display untrusted webpages.

**Comment by mcmxcdev** [comment]
> The best bet for security is [staying on the latest chromium release](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#can-i-see-these-security-bugs-so-that-i-can-back_port-the-fixes-to-my-downstream-project), which generally means the latest electron release (the chromium release is freezed for a particular electron release, and security fixes are backported).

I think you misunderstood me: I am 100% in favor of upgrading to every new major version of Electron once it matured asap, but staying at the tip of every patch/minor release is just overhead where the scarce resources of Ferdium could be used in more beneficial ways.

**Comment by mcmxcdev** [comment]
Just tried to run the application with v26.2.0 and Ubuntu still doesn’t work. People report that v27 beta works fine again, so I would say we wait for the stable release and skip v26.

UPDATE: confirmed that Ferdium works as expected on Ubuntu with https://github.com/electron/electron/releases/tag/v27.0.0-beta.5

**Comment by vraravam** [comment]
Closing since electron v26 is broken and I am not contributing frequently to ferdium any more.

**Pull request closed without merging**
